### ISSUE TITLE
[FEAT]: Add the Dark Mode

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/React-Portfolio#10]
In this application, match the color of dark mode with the current color. You can add dark colors as deep blue for the dark mode version.

For any query just ask the question in a comment.

Add a button in the bottom left corner with float: sticky;

**Comment by Anureng** [comment]
can you assign me ??

**Comment by Jilesh980** [comment]
Hi @devjainofficial  i have worked on this issue can you please assign me and review it. thanks.

**Comment by nguyenthihuynhgiao** [comment]
Hi, you can assigned for me

**Comment by ashish07-07** [comment]
can you explain the issue in detail

**Comment by devjainofficial** [comment]
> can you explain the issue in detail

I want a dark mode for the application, where the primary(light mode) should be the one already is. And the secondary color(dark mode) should be deep blue. Create one button in the bottom left corner with sticky positioning, so user can switch from light mode to dark mode and vice versa anytime.
