### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/React-Portfolio#7]
Add Dark mode using toggle button
![image](https://github.com/devjainofficial/React-Portfolio/assets/69387311/7c5bb415-a8b8-4d67-818a-47416f89c871)

**Comment by Baburao-sanivada** [comment]
hey @devjainofficial can i work on this issue

**Comment by Baburao-sanivada** [comment]
Hey @devjainofficial can you specify what are the colours you are expecting while on darkmode?

**Comment by devjainofficial** [comment]
you can use a deep blue color or add what is more preferable for website.

**Comment by devjainofficial** [comment]
@Baburao-sanivada How's the progress of the issue.

**Comment by Baburao-sanivada** [comment]
Sorry @devjainofficial I am bit busy with my office work could you assign the issue to some one else

**Comment by devjainofficial** [comment]
Okay not a problem
